image: alpine/edge
secrets:
  - 012b0f80-4054-4a40-9590-e509f20b7871
sources:
  - https://git.sr.ht/~rolandog/dotpub
tasks:
  - mirror-to-github: |
      cd ~/dotpub
      pwd
      echo -e "Host github.com\n    IdentityFile ~/.ssh/012b0f80-4054-4a40-9590-e509f20b7871\n    IdentitiesOnly yes\n    BatchMode yes\n" >> ~/.ssh/config
      cat ~/.ssh/config
      echo "|1|GmdxzOsXhCTX8+iESYHPIsCch6o=|P8Dc+wTPJvm4ZmKHdhP7B3ChsYg= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> ~/.ssh/known_hosts
      cat ~/.ssh/known_hosts
      git remote add github git@github.com:rolandog/dotpub.gitZZZ
      git branch -M main
      git push -u github --prune github +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/* main
      echo "done"

