#!/usr/bin/sh

### Identification
# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
  debian_chroot="$(cat /etc/debian_chroot)"
fi

### colors
# test for NO_COLOR https://no-color.org/
if [ -z "${NO_COLOR}" ]; then
  # colored GCC warnings and errors
  export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

  # enable color support of ls and also add handy aliases
  if [ -x /usr/bin/dircolors ]; then
    if [ -r "${XDG_CONFIG_HOME}/dircolors" ]; then
      eval "$(dircolors -b "${XDG_CONFIG_HOME}/dircolors")"
    else
      eval "$(dircolors -b)"
    fi
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
  fi
fi


# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
prefer_color_prompt="yes"

# if running bash
if [ -n "${BASH_VERSION:-}" ]; then
  if [ -n "${prefer_color_prompt}" ] && [ -z "${NO_COLOR}" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >/dev/null 2>&1; then
      # We have color support; assume it's compliant with Ecma-48
      # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
      # a case would tend to support setf rather than setaf.)
      # set a fancy prompt (non-color, unless we know we "want" color)
      case "${TERM}" in
        xterm-color|*-256color) color_prompt="yes";;
      esac
    else
      color_prompt=
    fi
  fi

  if [ "${color_prompt}" = "yes" ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
  else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
  fi

  # If this is an xterm set the title to user@host:dir
  case "$TERM" in
    xterm*|rxvt*)
      PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]${PS1}"
      ;;
    "dumb")
      PS1="> "
      ;;
    *)
      ;;
  esac

# if not running bash
else
  : "${USER=$(id -un)}" "${HOSTNAME=$(uname -n)}"
  # if da(sh)
  if [ "${0}" = "dash" ]; then
    # user @ computer
    PS1='${USER}@${HOSTNAME}'
    if echo "${PWD}" | grep -qE "^${HOME}" -; then
      # user @ computer : ~/foo
      PS1="${PS1}"':~${PWD#${HOME}}'
    else
      # user @ computer : /etc
      PS1="${PS1}"':${PWD}'
    fi
    # if effective user id is root
    if [ "$(id -u)" = "0" ]; then
      PS1="${PS1}# "
    else
      PS1="${PS1}\$ "
    fi
  # test for dumb terminal
  else
    case "$TERM" in
      "dumb")
        PS1="> "
        ;;
      *)
        ;;
    esac
  fi
fi

export PS1

unset color_prompt prefer_color_prompt

