#!/usr/bin/sh

# ~/.bash_logout: executed by bash(1) when login shell exits.

# when leaving the console clear the screen to increase privacy

# if running bash
if [ -n "${BASH_VERSION:-}" ]; then
  if [ "${SHLVL}" = 1 ]; then
    if [ -x /usr/bin/clear_console ]; then
      /usr/bin/clear_console -q
    fi
  fi
fi

