# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

### Test if interactive
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

### History
# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

### Window size
# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

### Pathname expansion
# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

### Compatibility
# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

### Identification
# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

### Color definitions
# You may want to put all your additions into a separate file like
# $XDG_CONFIG_HOME/bash/bash_colors, instead of adding them here
# directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.
if [ -f $XDG_CONFIG_HOME/bash/bash_colors ]; then
    . $XDG_CONFIG_HOME/bash/bash_colors
fi

### Alias definitions
# You may want to put all your additions into a separate file like
# $XDG_CONFIG_HOME/bash/bash_aliases, instead of adding them here
# directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.
if [ -f $XDG_CONFIG_HOME/bash/bash_aliases ]; then
    . $XDG_CONFIG_HOME/bash/bash_aliases
fi

### Completions
# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

### Custom definitions
# You may want to put all your additions into a separate file like
# $XDG_CONFIG_HOME/bash/bash_custom, instead of adding them here
# directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.
if [ -f $XDG_CONFIG_HOME/bash/bash_custom ]; then
    . $XDG_CONFIG_HOME/bash/bash_custom
fi

### XDG support
# add support for the XDG Base Directory Specification with some
# workarounds or solutions.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.
# See https://wiki.archlinux.org/title/XDG_Base_Directory
if [ -f $XDG_CONFIG_HOME/bash/bash_xdg ]; then
    . $XDG_CONFIG_HOME/bash/bash_xdg
fi

