#!/usr/bin/sh

### ls
# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# permissions
alias perms="stat -c '%a - %n'"

### neofetch
if [ -x /usr/bin/neofetch ]; then
  # test for NO_COLOR
  if [ -z "$NO_COLOR" ]; then
    alias system='neofetch'
  else
    alias system='neofetch --stdout'
  fi
fi

### Custom commands
# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
#   sleep 10; soundalert
alias alert='notify-send --urgency=low -i "$([[ $? == 0 ]] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias soundalert='notify-send --urgency=low -i "$([[ $? == 0 ]] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*soundalert$//'\'')" && aplay -q $XDG_DATA_HOME/bash/wubba_lubba_dub-dub.wav'

### sorting by tld
# reverses column order in dsv's (dot-separated-values)
alias revdots="$(
cat <<- "EOF"
awk 'BEGIN{FS=OFS="."}{for(i=NF;i>=1;i--)printf "%s%s", $i, (i>1?OFS:ORS)}'
EOF
)"
